import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Layout } from "../components/layout";

const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
